- name: variables
  hosts: local
  connection: local
  vars: #play level variables, globle variables
    course: "Devops with aws"
    duration: "100HRS"
    trainer: "Siavkumar"
  tasks:
  - name: print the variables
    ansible.builtin.debug:
      msg: "Course is {{ course }}, Duration is {{ duration }}, Trainer is {{ trainer }}" 