- name: variables
  hosts: local
  connection: local
  vars:
    course: "Devops with aws"
    duration: "120HRS"
    trainer: "Sivakumar"
  tasks:
  - name: print the task level variables
    vars: #task level variables, local variables
      course: "ansible"
      duration: "100HRS"
      trainer: "Sivakumar"
    ansible.builtin.debug:
      msg: "Course is {{course}}, Duration is {{duration}}, Trainer is {{trainer}}"
  - name: print the play level varibles
    ansible.builtin.debug:
      msg: "Course is {{course}}, Duration is {{duration}}, Trainer is {{trainer}}"