- name: install packages
  hosts: web
  become: yes
  tasks:
  - name: 'install "{{ item }}" packages'
    ansible.builtin.packages:
      name: "{{ item }}"
      state: present
    loop:
    - mysql
    - gcc
    - zip
    - git
