- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefind variable
    ansible.builtin.debug:
      msg: "Hello {{ person | default('Ashok')}}"

  - name: convert string to list
    vars:
      fruits: "apple, mango, carrot, goa" #string
    ansible.builtin.debug:
      msg: "fruits are: {{fruits | split(',')}}"     