- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefind variable
    ansible.builtin.debug:
      msg: "Hello {{ person | default('Ashok')}}"

  - name: convert string to list
    vars:
      fruits: "apple, mango, carrot, goa" #string
    ansible.builtin.debug:
      msg: "fruits are: {{ fruits | split(',') }}"     

  - name: convert map to list
    vars:
      course:
        name: ansible
        duration: 10hrs
        trainer: sivakumar
    ansible.builtin.debug:
      msg: "List is {{ course | dict2items }}"    

  - name: convert list to map
    vars:
      course:
      - {'key': 'name', 'value': 'ansible'}
      - {'key': 'duration', 'value': '10hrs'}
      - {'key': 'trainer', 'value': 'sivakumar'}  
    ansible.builtin.debug:
      msg: "Course info: {{ course | items2dict }}"    

  - name: convert upper to lower
    vars:
      name: "Ashok KumAr" 
    ansible.builtin.debug:
      msg: "{{ name | lower }}"    

  - name: convert lower to upper
    vars:
      name: "ashok Kumar" 
    ansible.builtin.debug:
      msg: "{{ name | upper }}"             