- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefind variable
    ansible.builtin.debug:
      msg: "Hello {{ person | default('Ashok')}}"

  - name: convert string to list
    vars:
      fruits: "apple, mango, carrot, goa" #string
    ansible.builtin.debug:
      msg: "fruits are: {{ fruits | split(',') }}"     

  - name: convert map to list
    vars:
      course:
        name: ansible
        duration: 10hrs
        trainer: sivakumar
    ansible.builtin.debug:
      msg: "List is {{ course | dict2items }}"        