- name: shell vs command
  hosts: local
  connection: local
  tasks:
  - name: execute ls command
    ansible.builtin.shell : ls > /tmp/output.txt

  - name: execute ls command in command module
    ansible.builtin.command : ls -lt
    register: c_result  

  - name: print result
    ansible.builtin.debug:
      msg: "{{ c_result }}" 